---
- name: Add nginx apt key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present

- name: Add nginx repostiory
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx

- name: check directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /var/www/html

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: setup Resource limit (Permanent)
  template: src=limit.conf.j2 dest=/etc/security/limits.conf

- name: copy nginx default configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    backup: yes
  with_items:
    - fastcgi_params
    - robots.txt
    - mime.types
    - sites-available/default-php.conf
    - sites-available/default-php-ssl.conf
    - sites-available/default

- name: copy nginx default page
  copy: src=index.html dest=/var/www/html

- name: check /etc/ssl/dhparams
  stat: path=/etc/ssl/dhparams
  register: dhparams_file

- name: Generate dhparams
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048
  when: dhparams_file.stat.exists != false

- name: install nginx
  apt:
    name: nginx
    state: latest

- name: Restart nginx
  service: name=nginx state=restarted
