---
- hosts: localhost
  become: yes
  vars:
    backup_user: "vagrant"
    backup_group: "vagrant"
    backup_target: "/home/vagrant/www/project"
    backup_remote_source:
      - /home/vagrant/tmp/ab
      - /home/vagrant/tmp
    backup_remote_user: vagrant
    backup_remote_host: "127.0.0.0"
    backup_private_key_path: "/home/vagrant/.ssh/id_rsa"
    backup_lock_path: "/home/vagrant/cron.lock"
  tasks:
    - name: Creates directory
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ backup_user }}"
        group: "{{ backup_group }}"
        mode: 0775
        recurse: yes
      with_items:
        - "{{ backup_target }}"
        - "{{ backup_lock_path }}"
    - name: Create rsync cron job
      cron:
        name: "Sync {{ item }}"
        job: "flock -w 0 {{ backup_lock_path }}/{{ item | hash('md5') }} rsync -a --delete -e \"ssh -i {{ backup_private_key_path }}\" {{ item }} {{ backup_target }}"
        state: present
        user: root
        special_time: hourly
      with_items:
        - "{{ backup_remote_source }}"
